# frozen_string_literal: true

require_relative "_sample_helper"

key = SDFSample::DEFAULT_ENC_KEY
key_id = Integer(ENV.fetch("KEY_ID", "1"))
value = ENV.fetch("VALUE", SDFSample::DEFAULT_PHONE).b.freeze
aad = SDFSample.aad.freeze
envelope = SecureDBFields::Crypto.encrypt(value, key: key, aad: aad, key_id: key_id)
out_path = ENV.fetch("OUT", "/tmp/secure_db_fields_mysql_decrypt_payload.sql")

File.open(out_path, "wb") do |f|
  f.puts "-- Generated by samples/mysql_udf_prepare_decrypt_payload.rb"
  f.puts "-- Requires SDF_ENC_KEY_#{key_id}_HEX or SDF_ENC_KEY_HEX in the MySQL UDF key file."
  f.puts "SET @sdf_sample_envelope = UNHEX('#{SDFSample.hex(envelope)}');"
  f.puts "SET @sdf_sample_aad = UNHEX('#{SDFSample.hex(aad)}');"
  f.puts "SET @sdf_sample_plaintext = '#{value.gsub("'", "''")}';"
end

puts "wrote=#{out_path}"
puts "envelope_bytes=#{envelope.bytesize}"
puts "aad_hex=#{SDFSample.hex(aad)}"
puts "plaintext=#{value}"
puts "required_key_hex=#{SDFSample.hex(key)}"
puts
puts "Next:"
puts "  mysql ... -e \"source #{out_path}; source samples/mysql_udf_decrypt_hot_path.sql; CALL sdf_decrypt_hot_loop(500000);\""
